import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "@/components/ui/toaster";
import WhatsAppChannelModal from "@/components/layout/WhatsAppChannelModal";
import { FirebaseClientProvider } from "@/firebase";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Nextgen",
  description: "Generated by create next app",
  icons: {
    icon: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJibGFjayI+PHBhdGggZD0iTTE3LjgzIDUuMTdBNTUuOTkgNS45OSAwIDAgMCAxMiAyYTUuOTkgNS45OSAwIDAgMC01LjgzIDMuMTdjLTEuOS44OS0zLjE3IDIuODItMy4xNyA1LjA1VjE5YzAgMS4xLjkgMiAyIDJoMTRjMS4xIDAgMi0uOSAyLTJ2LTguNzhjMC0yLjIzLTEuMjctNC4xNi0zLjE3LTUuMDV6TTEyIDRjMi4yMSAwIDQgMS43OSA0IDR2MUg4VjhjMC0yLjIxIDEuNzktNCA0LTR6Ii8+PC9zdmc+',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-gray-50 font-sans"
        )}
      >
        <AppProvider>
          <FirebaseClientProvider>
            <div className="min-h-screen flex flex-col">
              <Header />
              <main className="max-w-7xl mx-auto px-4 pb-4 pt-8 md:px-6 md:pb-6 md:pt-10 w-full flex-grow">
                {children}
              </main>
              <Footer />
            </div>
            <Toaster />
            <WhatsAppChannelModal />
          </FirebaseClientProvider>
        </AppProvider>
      </body>
    </html>
  );
}
